name: PbtPanelv2
main: com.pbtservers.pbtpanel.PbtPanelv2
api-version: 1.13
version: 2.4
description: Consola Basada en WebSocket
authors: [Pbt, Carlos Mesa]
commands:
  PbtPanel:
    description: Muestra la Versión y las Conexiones Activas
    permission: pbtpanel.pbtpanel
    usage: /PbtPanel
